# ./ansible-nginx/deploy.yml

- hosts: nginx
  vars: 
    WEBROOT: /home/cyue/CloudAsg2/webserver/html

  tasks:
    #- command: chdir={{playbook_dir}} sh env.sh
    #- include: 'tasks/install_nginx.yml'
    #- include: 'tasks/install_bottle.yml'
    - include: 'tasks/launch_server.yml'
